### ISSUE TITLE
AMD2 WD, new subclause 5.7.11.4 "Color glyph examples"

### ISSUE THREAD

**Issue by alerque** [MPEGGroup/OpenFontFormat#25]
Re editors note (p.23):

```markdown
The entire backdrop (outline, gradient-circle, 4 dots, the minute hand) is reusable for all versions of the clock:

[image]

The hour hand is reusable as a transformed glyph.
```

> Editor’s note: Is hour hand missing in this example?

No, the hour hand is not missing. The image is of the reusable **backdrop** as explained in the text leading up to the image ending in a colon. There is no image of the transformable hour hand glyph by itself, but I don't think there needs to be.

**Comment by vlevantovsky** [comment]
I suspect the confusing part was the misalignment of text and images. It would be logical to move the image of the backdrop to be the first in sequence of images to match the descriptive text.

**Comment by vlevantovsky** [comment]
Resolved, glyph examples were updated in the WD. Closing.
