### ISSUE TITLE
AMD2 WD, new subclause 5.7.11.2 "Graphical primitives"

### ISSUE THREAD

**Issue by vlevantovsky** [MPEGGroup/OpenFontFormat#28]
Consider replacing the description of the rendering process for radial gradients with a concrete reference to the spec where this process is described. In general, copying a content of one spec into another is not desirable, using references allows keeping the descriptions unambiguous and up to date (if and when an external specification is updated).

**Comment by PeterConstable** [comment]
The problem is this: the WHAT WG canvas spec gives the specific formula. However, it does not support alternate extend modes but assumes only padding. For that reason, the basic formulation is the same, but some details differ.

**Comment by vlevantovsky** [comment]
Has been adopted as part of the ISO/IEC 14496-22:2019 Working Draft AMD2, closing the issue.
