### ISSUE TITLE
AMD2 WD, new subclause 5.7.11.3 "Color table formats" - order of entries in the BaseGlyphV1Record 

### ISSUE THREAD

**Issue by vlevantovsky** [MPEGGroup/OpenFontFormat#29]
It makes sense to mandate a specific order of entries in the BaseGlyphV1Record. The suggestion is for entries to be ordered in the increasing glyphID order - NEEDS REVIEW.

**Comment by PeterConstable** [comment]
My draft in [colr_190_draft_201002.pdf](https://github.com/MPEGGroup/OpenFontFormat/files/5320174/colr_190_draft_201002.pdf) (see #20) included this:

>The records in the baseGlyphV1Records array should [be] sorted in increasing glyphID order.

**Comment by vlevantovsky** [comment]
@PeterConstable I think what you are saying is that you propose to include certain parts of your draft into a new input contribution that will summarize all proposed changes and will be submitted to the next WG meeting for consideration. I agree.

**Comment by vlevantovsky** [comment]
Resolved in [WD version 2](https://www.mpegstandards.org/wp-content/uploads/mpeg_meetings/133_OnLine/w19969.zip), closing.
