### ISSUE TITLE
Remove the Wiki

### ISSUE THREAD

**Issue by davelab6** [MPEGGroup/OpenFontFormat#3]
An Admin user can go to https://github.com/MPEGGroup/OpenFontFormat/settings/ and turn off the "Wiki" part of the repo. 

This is redundant with the contents of the repo itself, and lacks the full features of the Pull Request and Issue Tracking system. Now that Github itself has a 'pencil icon' for all files within a repo itself, for instant online editing, Github Wikis are totally unnecessary.

**Comment by vlevantovsky** [comment]
Done.
