### ISSUE TITLE
AMD2 WD, new subclause 5.7.11.3 "Color table formats" - description of the ColorIndex record

### ISSUE THREAD

**Issue by vlevantovsky** [MPEGGroup/OpenFontFormat#31]
A description of the "alpha" value is proposed as an informative note. It may be useful to expand this note and/or make it a part of the spec language - NEEDS REVIEW.

**Comment by PeterConstable** [comment]
I don't think it should be an informative note. In my draft [colr_190_draft_201002.pdf](https://github.com/MPEGGroup/OpenFontFormat/files/5320174/colr_190_draft_201002.pdf) (see #20), the content was basically the same except it was not a note.

**Comment by vlevantovsky** [comment]
Resolved as part of the ISO/IEC 14496-22:2019 Working Draft AMD2, closing the issue.
