### ISSUE TITLE
AMD2 WD, new subclause 5.7.11.3 "Color table formats" - order of entries in the ColorLine table

### ISSUE THREAD

**Issue by vlevantovsky** [MPEGGroup/OpenFontFormat#32]
It makes sense to define a specific order of entries in the colorStops array. The suggestion is for entries to be ordered in the increasing stopOffset order - NEEDS REVIEW. This is currently added as an informative note, may need to be converted to the spec proper.
Also, a description of color line positioning in relation to the glyph design grid may be needed.

**Comment by PeterConstable** [comment]
Per ISO procedures, part 2, NOTEs must not include "shall"/"should" statements. In my draft [colr_190_draft_201002.pdf](https://github.com/MPEGGroup/OpenFontFormat/files/5320174/colr_190_draft_201002.pdf) (see #20), this statement was not a note.

**Comment by vlevantovsky** [comment]
Right, it wasn't proposed as a note in your version of the text, but your text was not part of the original submission. Adding a note is within a realm of what project editor can do, this is why I added it as a note with the comment to revise it and make it part of the spec proper. 
For as long as we all agree that this should be a normative language, we can easily make this change as part of the new submission.

**Comment by vlevantovsky** [comment]
Resolved as part of the ISO/IEC 14496-22:2019 Working Draft AMD2, closing the issue.
