### ISSUE TITLE
AMD2 WD, new additions in subclause 7.2.3 - VarFixed record

### ISSUE THREAD

**Issue by vlevantovsky** [MPEGGroup/OpenFontFormat#33]
VarFixed record is intended to be used for variation of floating point values, such as variation space coordinates, defined in Fixed (16.16) format. While the actual value is defined as Fixed (an equivalent representation of 32-bit unsigned integer), both inner and outer variation indices are defined as 'uint16' values. NEEDS REVIEW.

**Comment by drott** [comment]
@vlevantovsky do you mean this issue to clarify how to vary a 16.16 fixed point number? As discussed here: https://github.com/googlefonts/colr-gradients-spec/issues/29 ?

**Comment by vlevantovsky** [comment]
@drott Thank you Dominik, and yes - the discussion you linked to (as part of the original draft) is exactly what I expected to happen at some point. The resolution of the technical issues with VarFixed (and 32-bit value variations in general) would need to be brought back to the AHG as part of the submission for WD proposed updates.

**Comment by PeterConstable** [comment]
The outer/inner indices are indices into ItemVariationStore arrays. These are intentionally 16-bit. The size of the item being varied is orthogonal to the size of the indices. The current draft text is correct as is.

**Comment by vlevantovsky** [comment]
I believe this issue was resolved, closing.
