### ISSUE TITLE
Proposed amendment to 7.2.3 needs improvement.

### ISSUE THREAD

**Issue by PeterConstable** [MPEGGroup/OpenFontFormat#34]
The WD currently states wrt 7.2.3:

>_Add the following text after the first four paragraphs (prior to ItemVariationStore table description):_

The topic of new section **Associating target items...** is generic, which is reasonable. But that scope would include content currently discussed in the fourth paragraph, so that paragraph (or a revision of it) should follow the new heading. 

Secondly, the wording currently proposed to be added after that heading focuses only on the new structures related to COLR v1. To make the section reflect the general scope suggested by the heading, it should represent the different ways used to associate target items with variation data in comparable ways.

For these reasons, I suggest that the changes in 7.2.3 should include the revisions I included in [otvarcommonformats_draft_200928_delta-from-183.pdf](https://github.com/MPEGGroup/OpenFontFormat/files/5294029/otvarcommonformats_draft_200928_delta-from-183.pdf) (see #20).

This includes a revision of the fourth paragraph along with other inserted text.

Thus, I would suggest the proposed amendment say, 
>_Replace the fourth paragraph of 7.2.3 ("Variation data is comprised...") with the following text:_

And that the proposed replacement text include the revised paragraph and following bullet points that are shown in [otvarcommonformats_draft_200928_delta-from-183.pdf](https://github.com/MPEGGroup/OpenFontFormat/files/5294029/otvarcommonformats_draft_200928_delta-from-183.pdf).

**Comment by vlevantovsky** [comment]
The working draft in it's current form contains the contents that were part of the original input contribution (which was based on the original COLR v1 proposal and did not include revisions you summarized in otvarcommonformats_draft), and editorial language added to give at least a minimal level of descriptive text, with the goal that this will be revised later. 
Any revisions are possible and very much welcome, we just need to prepare and submit them as input contribution to the WG. I am happy to use the language you proposed, if there are no objections to it.

**Comment by vlevantovsky** [comment]
Resolved as part of the ISO/IEC 14496-22:2019 Working Draft AMD2, closing the issue.
