### ISSUE TITLE
W3C Compositing and Blending Level 1 must be a normative reference

### ISSUE THREAD

**Issue by PeterConstable** [MPEGGroup/OpenFontFormat#35]
In the current WD, this is cited in the bibliography. That's not acceptable: implementation of this spec is necessarily dependent on the details of the compositing/blending modes given in the W3C spec.

**Comment by vlevantovsky** [comment]
According to ISO Directives (part 2), only finalized published documents (either published by ISO/IEC or other standards organizations) can be used as normative references. W3C Recommendations are recognized as ratified published standards, but Working Drafts and Candidate Recommendations cannot be used as part of normative references. This is why I added them to Bibliography, the same way we reference e.g. SVG2 and CSS Custom Properties for Cascading Variables (where both are still in CR stage, references [17, 18].
W3C Compositing and Blending Level 1 is also a Candidate Recommendation, this is why I included it a bibliographic reference.

**Comment by PeterCon** [comment]
Well, I'm reading the ISO Directives, Part 2, 10.2 "Permitted referenced documents", and I don't see anything mentioning "finalized".

>10.2 Permitted referenced documents
>Normatively referenced documents shall be documents published by ISO or IEC. In the absence
>of appropriate ISO or IEC documents, those published by other bodies may be listed as normative
>references provided that
>a) the referenced document is recognized by the committee as having wide acceptance and
>authoritative status,
>b) the committee has the agreement of the authors or publishers (where known) of the referenced
>document for its inclusion as a reference,
>c) the authors or publishers (where known) have also agreed to inform the committee of their
>intention to revise the referenced document and what points the revision will affect,
>d) the document is available under commercial terms which are fair, reasonable and nondiscriminatory,
>and
>e) any patented item required for the implementation of the ISO and/or IEC deliverable in the
>referenced document is available to be licensed in accordance with subclause 2.14 of the ISO/IEC
>Directives, Part 1, 2018, “Reference to patented items”.
>
>Informative reference may be made to any other type of document. Informative references shall be
>listed in the Bibliography.
>
>ISO and IEC normatively referenced documents shall have reached at least the enquiry stage (40.20 DIS
>or CDV).

In fact, notice the last statement which contradicts your assertion. (And I can provide an example of an ISO standard that makes normative reference to a not-yet-published standard.)

**Comment by vlevantovsky** [comment]
I don't see any contradiction in what you quoted, the particular line of text only speaks of ISO/IEC DIS documents but that doesn't equate to W3C CR stage, which can still be changed or reversed to WD. In the past, the ISO Editors insisted that  CR should not be considered suitable for normative referencing - I will double-check and we still have plenty of time to change this if the document status changes.

**Comment by PeterCon** [comment]
>According to ISO Directives (part 2), only finalized published documents (either **published by ISO/IEC** or other standards organizations) can be used as normative references.

versus

>ISO and IEC normatively referenced documents shall have reached at least the enquiry stage (40.20 DIS
or CDV).

If ISO CS won't accept the CR, then a large portion of text from the W3C spec would need to be copied into OFF since the specification of each composition and blending mode is an essential requirement.

**Comment by vlevantovsky** [comment]
Alternatively, we can add any additional strong language to emphasize the importance of this reference, and to make sure that implementations strictly follow the specification of composition and blending modes described by the external reference. OT text doesn't make a distinction between normative and informative references - they are just external references - I don't see why we cannot add more language around this one to make sure that the intent is clear and unambiguous.

**Comment by vlevantovsky** [comment]
As a side note, I think the recent changes to the W3C Process 2020 give us enough ground to raise this issue with ISO Secretariat. The new Process allows for "evergreen" standard to be created - something that will be considered a published document, but never truly formalized / frozen, and is always treated as work in progress. Unless ISO CS will revise their directives, I do not see how these documents can ever be used as external normative references - this is definitely something we can use as a substantive argument for allowing normative references be made to "evergreen" standards.

**Comment by PeterCon** [comment]
I think the living, "evergreen" specifications are somewhat problematic when normatively referenced from a versioned spec like OFF. For instance, if WHAT WG were to change the algorithm for createRadialGradient because they incorporated extend modes, but with very different extend modes, then how would it be possible to evaluate if OFF implementation were conformant? (One more reason why the WHAT WG HTML spec is better as an informative reference.)

**Comment by vlevantovsky** [comment]
Resolved in the subsequent input contribution m55831 "Proposed updates for extending COLR table format and functionality", which has been incorporated as part of the ISO/IEC 14496-22:2019 Working Draft AMD2, closing the issue.
