### ISSUE TITLE
Proposed for AMD 2: update 6.4.1 Script tags

### ISSUE THREAD

**Issue by PeterCon** [MPEGGroup/OpenFontFormat#36]
I propose the following addition to Amendment 2, to synchronize script tags in OFF with OT 1.8.4 and Unicode 13.

-----
**6.4.1**

_Add new entries in the table of script tags for the following additions:_

| Script | Script tag |
|-|-|
| Chorasmian | 'chrs' |
| Dives Akuru | 'diak' |
| Elymaic | 'elym' |
| Khitan Small Script | 'kits' |
| Nandinagari | 'nand' |
| Nyiakeng Puachue Hmong | 'hmnp' |
| Wancho | 'wcho' |
| Yezidi | 'yezi' |

**Comment by vlevantovsky** [comment]
Included as part of the input contribution m55833 "Proposed new amendments for ISO/IEC 14496-22 AMD2", which has been incorporated as part of the ISO/IEC 14496-22:2019 Working Draft AMD2, closing the issue.
