### ISSUE TITLE
Proposed Optical Size recommended implementation changes

### ISSUE THREAD

**Issue by vlevantovsky** [MPEGGroup/OpenFontFormat#38]
The content of the changes has been a subject of the [extensive debate in the CSS WG](https://github.com/w3c/csswg-drafts/issues/4430) and the recommended specification change (based on the outcome of the discussion) is [summarized in the OT GitHub issue 310](https://github.com/MicrosoftDocs/typography-issues/issues/310#issuecomment-708643967).

The AHG should consider adding these changes as part of the AMD2 Working Draft.

**Comment by PeterCon** [comment]
Sounds like a good addition.

**Comment by davelab6** [comment]
@vlevantovsky how quickly can this go through? :)

**Comment by vlevantovsky** [comment]
@davelab6 These proposed changes are already a part of the [updated Working Draft AMD2](https://www.mpegstandards.org/wp-content/uploads/mpeg_meetings/133_OnLine/w19969.zip), they will be finalized at the same time as COLR v1 with other proposed changes (issues #36 and #37).

**Comment by vlevantovsky** [comment]
Included as part of the input contribution m55833 "Proposed new amendments for ISO/IEC 14496-22 AMD2", which has been incorporated as part of the ISO/IEC 14496-22:2019 Working Draft AMD2, closing the issue.
