### ISSUE TITLE
Add support for sweep gradients in COLR v1

### ISSUE THREAD

**Issue by PeterCon** [MPEGGroup/OpenFontFormat#39]
In the current WD, the enhancements for COLR v1 include linear and radial gradient. There is a third type of basic, colour gradient commonly recognized: sweep (or "conical" / "angular") gradients. This gradient type should also be added for COLR v1.

The necessary content revisions have been prepared in this submission: <https://github.com/googlefonts/colr-gradients-spec/blob/master/OFF_AMD2_WD.md>. Sub-clause 5.7.11.1.2.4 Sweep gradients is added, describing this type of gradient; but there are other changes needed in following parts of the content for 5.7.11.

**Comment by PeterConstable** [comment]
The [draft in the Google Fonts repo](https://github.com/googlefonts/colr-gradients-spec/blob/master/OFF_AMD2_WD.md) has been updated to address this issue. The following is the main pull request for that change:

* [Add PaintSweepGradient](https://github.com/googlefonts/colr-gradients-spec/pull/217)
* [PaintSweepGradient: rename x -> centerX, y -> centerY](https://github.com/googlefonts/colr-gradients-spec/pull/228)
* [Update sweep gradient per #250](https://github.com/googlefonts/colr-gradients-spec/pull/253)

**Comment by vlevantovsky** [comment]
Proposed changes are introduced by input contribution m56339.
