### ISSUE TITLE
[AMD2 WD: COLR v1] Address "TBDs" in working draft regarding open issues on radial gradients

### ISSUE THREAD

**Issue by PeterConstable** [MPEGGroup/OpenFontFormat#41]
The working draft presented at the January SC29 meeting (m55831-COLR_v1_updates-14496-22-AMD2.docx) had "TBDs" calling out two open issues regarding specification and behaviour of radial gradients:

> _TBD: What should the expected behavior be in the case of both circles exactly overlapping with r > 0? (Only the extensions get painted, but how?)_
> _TBD: We still need to specify required behavior for the case in which the transform really flattens the two circles, and the centers, to a line.>

These need to be addressed in the next working draft.

**Comment by PeterConstable** [comment]
The [draft in the Google Fonts repo](https://github.com/googlefonts/colr-gradients-spec/blob/master/OFF_AMD2_WD.md) has been updated to address this issue. The following is the main pull request for that change:

* [For radial gradient, clarify if circles are identical](https://github.com/googlefonts/colr-gradients-spec/pull/223)
* [Clarify result if radial gradient circles are flattened](https://github.com/googlefonts/colr-gradients-spec/pull/224)

While working on this, it was noticed that visual Moiré patterns can occur if the circles specifying a radial gradient are not quite identical. Also, in a variable font, if the circles are varying, then a sharp transition can occur. It was thought to be a good idea to call these things out in the text. The following PR has changes for this. (Addition of figures required renumbering of all subsequent figures.)

* [add note for rad grad re sharp transitions if rel'nship of circles vary](https://github.com/googlefonts/colr-gradients-spec/pull/206)

Also, another small wording change in the radial gradient algorithm was made:

* [Revise wording for radial gradient algorithm](https://github.com/googlefonts/colr-gradients-spec/pull/215)

**Comment by vlevantovsky** [comment]
Proposed changes have been incorporated as part of the input contribution m56341.
