### ISSUE TITLE
[AMD2 WD: COLR v1] Address "TBD" in working draft regarding interpolation of colours

### ISSUE THREAD

**Issue by PeterConstable** [MPEGGroup/OpenFontFormat#42]
The working draft presented at the January SC29 meeting (m55831-COLR_v1_updates-14496-22-AMD2.docx) had a "TBD" calling out specification for interpolation of colours:

> _TBD: Does interpolation of colors need further specification?_

This needs to be resolved in the working draft.

**Comment by PeterConstable** [comment]
The [draft in the Google Fonts repo](https://github.com/googlefonts/colr-gradients-spec/blob/master/OFF_AMD2_WD.md) has been updated to address this issue. The following is the main pull request for that change. Note that this introduces changes in 5.7.12 for the CPAL table.

* [Add CPAL edits re sRGB 'gamma' and interpolation](https://github.com/googlefonts/colr-gradients-spec/pull/214)
* [Change one more instance in CPAL of 'linear' to 'linear-light'](https://github.com/googlefonts/colr-gradients-spec/pull/259)

The following related change was also made:

* [Add wording to clarify color line intervals](https://github.com/googlefonts/colr-gradients-spec/pull/226)

**Comment by svgeesus** [comment]
This all looks great!

**Comment by vlevantovsky** [comment]
Proposed changes have been introduced by the input contribution m56340.
