### ISSUE TITLE
[AMD2 WD: COLR v1] Add paint formats for more compact representations in non-variable fonts

### ISSUE THREAD

**Issue by PeterConstable** [MPEGGroup/OpenFontFormat#43]
In the working draft presented at the January SC29 meeting (m55831-COLR_v1_updates-14496-22-AMD2.docx), various paint table formats have structures that allow for delta-set indices in variable fonts. In non-variable fonts, these fields are present but un-used. These result in significant size increases without benefit in non-variable fonts.

For example, for specifying a linear gradient, the size of the paint table is 40 bytes, not counting the ColorLine subtable; and 24 of 40 bytes (60%) is for un-used delta-set indices. The size of the ColorLine subtable is 8 × numStops + 3, of which 4 × numStops (36% to 50%) is for un-used delta-set indices.

The actual size impact on a non-variable, COLR v1 font will depend on the nature of the colour glyph descriptions used. Using preliminary versions of Google's Noto Emoji font using COLR v1, it was estimated that about 12% of the file size is un-used delta-set indices.

It would be worthwhile, then, to revise the proposed COLR v1 formats to allow for more compact representation in non-variable fonts.

The following are the v1 structures that include delta-set indices:

* ColorIndex record
* ColorStop record
* ColorLine table (by virtue of the contained ColorStop and ColorIndex records)
* PaintSolid (by virtue of the contained ColorIndex record)
* PaintLinearGradient (directly, and also in the ColorLine subtable)
* PaintRadialGradient (directly, and also in the ColorLine subtable)
* PaintSweepGradient (directly, and also in the ColorLine subtable)
* Affine2x3 record
* PaintTransform (by virtue of the Affine2x3 record)
* PaintTranslate
* PaintRotate
* PaintSkew

A few alternative designs have been considered by Google and Microsoft engineers:

- Additional non-variable paint table formats
- Add a flags field to relevant structures indicating whether members do or do not allow for variations
- Separate arrays in the COLR v1 table for variable and non-variable values of different types (FWORD, etc.), and revision of ColorIndex, etc., structures to have indices into these value arrays rather than containing values directly.

It was determined that additional non-variable paint table formats provide the best balance between improved efficiency for non-variable fonts and additional complexity in the structures.

Thus, additional paint (and member) formats for more-compact non-variable representation should be added; these would be non-variable counterparts to the structures listed above.

**Comment by PeterConstable** [comment]
The [draft in the Google Fonts repo](https://github.com/googlefonts/colr-gradients-spec/blob/master/OFF_AMD2_WD.md) has been updated to address this issue. The following is the main pull request for that change:

* [Start revisions to add no-var formats](https://github.com/googlefonts/colr-gradients-spec/pull/249)
* [Additional changes in 5.7.11 COLR to incorporate non-variable formats](https://github.com/googlefonts/colr-gradients-spec/pull/252)

**Comment by PeterConstable** [comment]
>Using preliminary versions of Google's Noto Emoji font using COLR v1, it was estimated that about 12% of the file size is un-used delta-set indices.

After updating Google's implementation to use the additional paint formats, the actual reduction in file size for Noto Emoji COLR v1 was 16%.

**Comment by svgeesus** [comment]
This looks like a useful addition! No need for non-variable fonts to pay a size tax.

**Comment by vlevantovsky** [comment]
Proposed changes have been incorporated as part of the input contribution m56342.
