### ISSUE TITLE
[AMD2 WD: COLR v1] Add discussion of bounding box and transformation in variable fonts

### ISSUE THREAD

**Issue by PeterConstable** [MPEGGroup/OpenFontFormat#44]
In the January working draft for AMD 2, it is noted that implementations can use the base glyph bounding box to allocate memory for the bitmap in which to composed the colour glyph. Something that is not called out, however, is that the colour glyph description can include transformations that may be variable (in a variable font), and that variation of the transformation could cause portions of the colour glyph to go outside the bounding box of the default glyph.

Some content should be added to call out this issue for implementers.

**Comment by PeterConstable** [comment]
The [draft in the Google Fonts repo](https://github.com/googlefonts/colr-gradients-spec/blob/master/OFF_AMD2_WD.md) has been updated to address this issue. The following is the main pull request for that change:

* [Add discussion of bounding box and variations](https://github.com/googlefonts/colr-gradients-spec/pull/255/files)

**Comment by vlevantovsky** [comment]
Proposed changes have been incorporated as part of the input contribution m56342.
