### ISSUE TITLE
Review and adopt DSIG table changes as part of AMD2

### ISSUE THREAD

**Issue by vlevantovsky** [MPEGGroup/OpenFontFormat#45]
The issues with DSIG have been a subject of ongoing discussions for quite some time. It's been [raised on the AHG list back in early 2016](https://lists.aau.at/pipermail/mpeg-otspec/2016-March/000701.html), and also recently - both [on the AHG list](https://lists.aau.at/pipermail/mpeg-otspec/2020-August/002119.html) and on [MS Typography GitHub](https://github.com/MicrosoftDocs/typography-issues/issues/455) There is still a time to discuss and include the changes into the current AMD2.

**Comment by HinTak** [comment]
Good that the suggested change is finally going in. What further discussion is needed? Not being rhetorical - there are presumably process difference between a change being accepted in the MS doc vs being accepted for the iso doc.

**Comment by vlevantovsky** [comment]
@HinTak I am not sure if more technical discussion is needed - the proposed draft changes have been shared as part of the MS Typography GitHub issue discussion. Since we are in early stages of AMD2 development, introducing this as yet another amended part is relatively easy - all that's needed is to review and agree with the proposed changes, and submit them to the next WG meeting as input contribution.

**Comment by ValZapod** [comment]
> What further discussion is needed

For example,
`About ttc header, the bulk of many old Microsoft shipped TTC also have a version 1 header rather than version 2. So that's another issue where the De facto signing implementation (does not reject v1 header) does not match the spec (which only states v2).
`
I only saw signed collection files in Windows itself though. But then again, they cannot be even installed normally last time I checked, but only by coping them to C:/Windows/Fonts, which cannot be opened in explorer normally, only by putting the path in Start menu.

**Comment by HinTak** [comment]
I believe old fonts not conforming to old spec, or old fonts not conforming to current spec, is only a point of (historical) interest. Anything goes for not-currently-shipping fonts, really. 

The procedure for installing fonts on windows, is off topic.

**Comment by ValZapod** [comment]
> is off topic.

And also I was wrong. It was just a bad ttc file, PTSans.ttc. It is now in 20H2 reported as corrupted. And also I tried other ttc with variable stuff -- it also worked, including new variable stuff. So it is just that file.

**Comment by vlevantovsky** [comment]
The proposed changes are now part of the input contribution m56343 "Proposed additional updates in ISO/IEC 14496-22 AMD2" submitted for consideration of the WG3 MPEG systems meeting.
