### ISSUE TITLE
Archive repo discussions in a mailman listserv?

### ISSUE THREAD

**Issue by davelab6** [MPEGGroup/OpenFontFormat#6]
As proposed in https://lists.aau.at/pipermail/mpeg-otspec/2020-August/002155.html

**Comment by vlevantovsky** [comment]
I am not sure it is a good idea considering the limitations of our only list, as described in https://lists.aau.at/pipermail/mpeg-otspec/2020-August/002162.html

**Comment by alerque** [comment]
If "following along in another venue" is the goal, issue comments to email is a pretty noisy and not terribly useful mechanism. If "archive discussion off Github" is the goal, all issue/comments/etc. can be retrieved from the API and could periodically be dumped elsewhere. Some meta data is lost in the process, but the basic content/names/times would come through. Honestly not sure that's needed though, this site isn't some fly-by-night operation.

**Comment by behdad** [comment]
> I am not sure it is a good idea considering the limitations of our only list, as described in https://lists.aau.at/pipermail/mpeg-otspec/2020-August/002162.html

That's irrelevant.

Yes, please request a W3C mailing list just for this group's email archives, and later the W3C CG github archives.

**Comment by davelab6** [comment]
> If "archive discussion off Github" is the goal

That was the goal I heard proposed; and I agree with @vlevantovsky that using the mpeg-otspec itself to do this would be a bad idea. However, when Vlad writes,

>> Considering the fact that the AHG email list is only active for as long as ... this AHG is re-established by its parent ISO WG (which happens at every WG meeting, 3-4 times a year)

That suggests to me an independent archive of both the mpeg-otspec list **and** https://github.com/MPEGGroup/OpenFontFormat discussions ought to be set up, given that both are public today, yet pass under a knife and risk deletion every 3 months.

**Comment by vlevantovsky** [comment]
> That suggests to me an independent archive of both the mpeg-otspec list and https://github.com/MPEGGroup/OpenFontFormat discussions ought to be set up, given that both are public today, yet pass under a knife and risk deletion every 3 months.

The AHG email list is not "under a knife risking a deletion every three months", I am sorry if my message gave you this wrong impression. (Our long history of operation and the ability to save and maintain email archives even when the list has transitioned from one host to another should give you some peace of mind.) The AHG will be formed for as long as its needed, and for as long as the ISO/IEC 14496-22 work will continue. AHG mandates may change over time but this is not a death sentence. To give you some perspective, the W3C WebFonts WG has been reformed (as in disbanded and reestablished again) three times in 2009, 2012 and 2018, with new charters developed and approved by the W3C AC defining new scope and deliverables. And, as @alerque already mentioned, the GitHub isn't a fly-by-night operation so I am not too concerned about our repo content. 

On top of it all, we need to be respectful of organizational boundaries - asking W3C to setup and maintain an archive for ISO work discussions isn't appropriate.

**Comment by davelab6** [comment]
Thanks for clarifying and I apologise that I misunderstood. I agree that GitHub isn't a fly-by-night operation, and I would expect plenty of notice and features to migrate elsewhere if/when it is eventually shut down (such as Google gave for the end of code.google.com)
